name 'chef_classroom'
maintainer 'George Miranda (<gmiranda@chef.io>)'
maintainer_email 'gmiranda@chef.io'
license 'MIT'
description 'Installs/Configures chef_classroom'
long_description 'Installs/Configures chef_classroom'
version '0.4.0'

depends 'chef_workstation'
depends 'guacamole'
depends 'chef_portal'
