name 'chef_classroom'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_classroom'
long_description 'Installs/Configures chef_classroom'
version '0.1.0'
